
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EECIP.App_Logic.DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Badge
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Badge()
    {

        this.MembershipUser_Badge = new HashSet<MembershipUser_Badge>();

    }


    public System.Guid Id { get; set; }

    public string Type { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }

    public string Description { get; set; }

    public string Image { get; set; }

    public Nullable<int> AwardsPoints { get; set; }

    public bool ACT_IND { get; set; }

    public int SORT_SEQ { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MembershipUser_Badge> MembershipUser_Badge { get; set; }

}

}
