
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EECIP.App_Logic.DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Category
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Category()
    {

        this.Category1 = new HashSet<Category>();

        this.Topics = new HashSet<Topic>();

    }


    public System.Guid Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsLocked { get; set; }

    public bool ModerateTopics { get; set; }

    public bool ModeratePosts { get; set; }

    public int SortOrder { get; set; }

    public System.DateTime DateCreated { get; set; }

    public string Slug { get; set; }

    public string PageTitle { get; set; }

    public string Path { get; set; }

    public string MetaDescription { get; set; }

    public string Colour { get; set; }

    public string Image { get; set; }

    public Nullable<System.Guid> Category_Id { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Category> Category1 { get; set; }

    public virtual Category Category2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Topic> Topics { get; set; }

}

}
