
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EECIP.App_Logic.DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class MembershipUser_Badge
{

    public int MembershipUser_Id { get; set; }

    public System.Guid Badge_Id { get; set; }

    public System.DateTime DateEarned { get; set; }



    public virtual T_OE_USERS T_OE_USERS { get; set; }

    public virtual Badge Badge { get; set; }

}

}
