
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EECIP.App_Logic.DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Poll
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Poll()
    {

        this.Topics = new HashSet<Topic>();

        this.PollAnswers = new HashSet<PollAnswer>();

    }


    public System.Guid Id { get; set; }

    public bool IsClosed { get; set; }

    public System.DateTime DateCreated { get; set; }

    public Nullable<int> ClosePollAfterDays { get; set; }

    public int MembershipUser_Id { get; set; }



    public virtual T_OE_USERS T_OE_USERS { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Topic> Topics { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PollAnswer> PollAnswers { get; set; }

}

}
