//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EECIP.App_Logic.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_MON_TOPIC_VOTE
    {
        public int YR { get; set; }
        public int MON { get; set; }
        public string Name { get; set; }
        public Nullable<int> CNT { get; set; }
    }
}
