
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EECIP.App_Logic.DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class T_OE_REF_TAGS
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public T_OE_REF_TAGS()
    {

        this.T_OE_PROJECTS = new HashSet<T_OE_PROJECTS>();

        this.T_OE_PROJECTS1 = new HashSet<T_OE_PROJECTS>();

        this.T_OE_PROJECTS2 = new HashSet<T_OE_PROJECTS>();

        this.T_OE_PROJECTS3 = new HashSet<T_OE_PROJECTS>();

    }


    public int TAG_IDX { get; set; }

    public string TAG_NAME { get; set; }

    public string TAG_CAT_NAME { get; set; }

    public bool USER_CREATE_IND { get; set; }

    public Nullable<int> CREATE_USERIDX { get; set; }

    public Nullable<System.DateTime> CREATE_DT { get; set; }



    public virtual T_OE_REF_TAG_CATEGORIES T_OE_REF_TAG_CATEGORIES { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<T_OE_PROJECTS> T_OE_PROJECTS { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<T_OE_PROJECTS> T_OE_PROJECTS1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<T_OE_PROJECTS> T_OE_PROJECTS2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<T_OE_PROJECTS> T_OE_PROJECTS3 { get; set; }

}

}
