
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EECIP.App_Logic.DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class T_OE_APP_SETTINGS_CUSTOM
{

    public int SETTING_CUSTOM_IDX { get; set; }

    public string TERMS_AND_CONDITIONS { get; set; }

    public string ANNOUNCEMENTS { get; set; }

}

}
