//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EECIP.App_Logic.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OE_REF_EMAIL_TEMPLATE
    {
        public string EMAIL_TEMP_ID { get; set; }
        public string EMAIL_TEMP_NAME { get; set; }
        public string EMAIL_TEMP_DESC { get; set; }
        public string EMAIL_TEMP_SUBJECT { get; set; }
        public string EMAIL_TEMP_BODY_HTML { get; set; }
        public string EMAIL_TEMP_BODY_TXT { get; set; }
        public Nullable<int> CREATE_USERIDX { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public Nullable<int> MODIFY_USERIDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
    }
}
