
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EECIP.App_Logic.DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class T_OE_DOCUMENTS
{

    public System.Guid DOC_IDX { get; set; }

    public byte[] DOC_CONTENT { get; set; }

    public string DOC_NAME { get; set; }

    public string DOC_TYPE { get; set; }

    public string DOC_FILE_TYPE { get; set; }

    public Nullable<int> DOC_SIZE { get; set; }

    public string DOC_COMMENT { get; set; }

    public string DOC_AUTHOR { get; set; }

    public Nullable<System.Guid> PROJECT_IDX { get; set; }

    public Nullable<int> ORG_ENT_SVCS_IDX { get; set; }

    public Nullable<int> CREATE_USERIDX { get; set; }

    public Nullable<System.DateTime> CREATE_DT { get; set; }

    public Nullable<int> MODIFY_USERIDX { get; set; }

    public Nullable<System.DateTime> MODIFY_DT { get; set; }



    public virtual T_OE_ORGANIZATION_ENT_SVCS T_OE_ORGANIZATION_ENT_SVCS { get; set; }

    public virtual T_OE_PROJECTS T_OE_PROJECTS { get; set; }

}

}
