
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EECIP.App_Logic.DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class T_OE_ORGANIZATION
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public T_OE_ORGANIZATION()
    {

        this.T_OE_ORGANIZATION_ENT_SVCS = new HashSet<T_OE_ORGANIZATION_ENT_SVCS>();

        this.T_OE_USERS = new HashSet<T_OE_USERS>();

        this.T_OE_PROJECTS = new HashSet<T_OE_PROJECTS>();

        this.T_OE_ORGANIZATION_TAGS = new HashSet<T_OE_ORGANIZATION_TAGS>();

        this.T_OE_ORGANIZATION_EMAIL_RULE = new HashSet<T_OE_ORGANIZATION_EMAIL_RULE>();

    }


    public System.Guid ORG_IDX { get; set; }

    public string ORG_ABBR { get; set; }

    public string ORG_NAME { get; set; }

    public string STATE_CD { get; set; }

    public Nullable<int> EPA_REGION { get; set; }

    public Nullable<bool> ALLOW_JOIN_IND { get; set; }

    public string CLOUD { get; set; }

    public string API { get; set; }

    public bool ACT_IND { get; set; }

    public bool SYNC_IND { get; set; }

    public Nullable<int> CREATE_USERIDX { get; set; }

    public Nullable<System.DateTime> CREATE_DT { get; set; }

    public Nullable<int> MODIFY_USERIDX { get; set; }

    public Nullable<System.DateTime> MODIFY_DT { get; set; }

    public string ORG_TYPE { get; set; }



    public virtual T_OE_REF_REGION T_OE_REF_REGION { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<T_OE_ORGANIZATION_ENT_SVCS> T_OE_ORGANIZATION_ENT_SVCS { get; set; }

    public virtual T_OE_REF_STATE T_OE_REF_STATE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<T_OE_USERS> T_OE_USERS { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<T_OE_PROJECTS> T_OE_PROJECTS { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<T_OE_ORGANIZATION_TAGS> T_OE_ORGANIZATION_TAGS { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<T_OE_ORGANIZATION_EMAIL_RULE> T_OE_ORGANIZATION_EMAIL_RULE { get; set; }

}

}
