//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EECIP.App_Logic.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OE_SYS_SEARCH_LOG
    {
        public int SYS_SEARCH_LOG_ID { get; set; }
        public System.DateTime LOG_DT { get; set; }
        public Nullable<int> LOG_USERIDX { get; set; }
        public string LOG_TERM { get; set; }
    }
}
