//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EECIP.App_Logic.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OE_PROJECT_ORGS
    {
        public System.Guid PROJECT_ORG_IDX { get; set; }
        public System.Guid PROJECT_IDX { get; set; }
        public Nullable<System.Guid> ORG_IDX { get; set; }
        public Nullable<int> CREATE_USERIDX { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public Nullable<int> MODIFY_USERIDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
    
        public virtual T_OE_ORGANIZATION T_OE_ORGANIZATION { get; set; }
        public virtual T_OE_PROJECTS T_OE_PROJECTS { get; set; }
    }
}
