
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EECIP.App_Logic.DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class T_OE_PROJECT_URLS
{

    public System.Guid PROJECT_URL_IDX { get; set; }

    public Nullable<System.Guid> PROJECT_IDX { get; set; }

    public string PROJECT_URL { get; set; }

    public string PROJ_URL_DESC { get; set; }



    public virtual T_OE_PROJECTS T_OE_PROJECTS { get; set; }

}

}
