
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EECIP.App_Logic.DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Topic_Tags
{

    public System.Guid Topic_Id { get; set; }

    public string TopicTagAttribute { get; set; }

    public string TopicTag { get; set; }



    public virtual Topic Topic { get; set; }

}

}
