//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EECIP.App_Logic.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_DEFINED_TAGS
    {
        public string PROJECT_TAG_NAME { get; set; }
        public string UserTagType { get; set; }
        public Nullable<int> CNT { get; set; }
    }
}
