INSERT INTO [T_OE_PROJECT_ORGS]([PROJECT_ORG_IDX], PROJECT_IDX, ORG_IDX, CREATE_USERIDX, CREATE_DT, MODIFY_USERIDX, MODIFY_DT)
SELECT NEWID(),PROJECT_IDX, ORG_IDX, CREATE_USERIDX, CREATE_DT, MODIFY_USERIDX, MODIFY_DT
FROM T_OE_PROJECTS
WHERE ORG_IDX IS NOT NULL;

GO


UPDATE T_OE_PROJECTS set ORG_IDX = null;

GO