CREATE TABLE [dbo].[T_OE_PROJECT_URLS](
	[PROJECT_URL_IDX] [uniqueidentifier] NOT NULL DEFAULT newid(),
	[PROJECT_IDX] [uniqueidentifier] NULL,	
	[PROJECT_URL] [varchar](200) NULL,
	[PROJ_URL_DESC] [varchar](max) NULL,		
 CONSTRAINT [PK_T_OE_PROJECTS_URL] PRIMARY KEY CLUSTERED  ([PROJECT_URL_IDX] ASC),
 FOREIGN KEY ([PROJECT_IDX]) references [T_OE_PROJECTS] ([PROJECT_IDX]) ON UPDATE CASCADE ON DELETE CASCADE,
) ON [PRIMARY]

GO	 

