INSERT INTO T_OE_PROJECT_URLS(PROJECT_URL_IDX, PROJECT_IDX, PROJECT_URL, PROJ_URL_DESC)
SELECT NEWID(),PROJECT_IDX AS PROJECT_IDX, PROJECT_URL AS PROJECT_URL,''
FROM T_OE_PROJECTS
WHERE PROJECT_URL <> ''
